<?php
/**
 * Contains customizations for WooCommerce Admin
 *
 * @package WC_Calypso_Bridge/Classes
 * @since   1.0.17
 * @version 1.0.0
 */

defined( 'ABSPATH' ) || exit;

/**
 * WC Calypso Bridge WooCommerce Admin
 */
class WC_Calypso_Bridge_WooCommerce_Admin {
	/**
	 * Class instance.
	 *
	 * @var WC_Calypso_Bridge_WooCommerce_Admin instance
	 */
	protected static $instance = false;

	/**
	 * Get class instance
	 */
	public static function factory() {
		if ( ! self::$instance ) {
			self::$instance = new self();
		}
		return self::$instance;
	}

	/**
	 * Initialize the class
	 */
	public function init() {
		if ( ! apply_filters( 'wc_calypso_bridge_allow_wca_devdocs', false ) ) {
			$this->remove_devdocs_menu_item();
		}
	}

	/**
	 * Remove the Dev Docs menu item unless allowed by the `wc_admin_get_feature_config` filter.
	 */
	public function remove_devdocs_menu_item() {
		if ( ! function_exists( 'wc_admin_get_feature_config' ) ) {
			/**
			 * Override the default local configuration file generated by WC Admin.
			 */
			function wc_admin_get_feature_config() {
				return array(
					'activity-panels' => true,
					'analytics' => true,
					'analytics-dashboard' => true,
					'analytics-dashboard/customizable' => true,
					'onboarding' => true,
					'store-alerts' => true,
				);
			}
		}
	}
}

WC_Calypso_Bridge_WooCommerce_Admin::factory()->init();
