<?php

namespace Automattic\WooCommerce\Admin\Features\OnboardingTasks\Tasks;

use Automattic\WooCommerce\Admin\Features\Features;
use Automattic\WooCommerce\Admin\Features\OnboardingTasks\Tasks\Products;

/**
 * HeadstartProducts Task
 */
class HeadstartProducts extends Products {
	/**
	 * Task completion.
	 *
	 * @return bool
	 */
	public function is_complete() {
		return self::has_products();
	}

	/**
	 * Check if the store has any published products,
	 * but exclude sample products generated by Headstart themes.
	 *
	 * @return bool
	 */
	public static function has_products() {
		$product_query = array(
			'post_type' => 'product',
			'post_status' => 'publish',
			'fields' => 'ids',
			'meta_query' => array(
				array(
					'key' => '_headstart_post',
					'compare' => 'NOT EXISTS'
				)
			)
		);
		$products = get_posts( $product_query );
		$product_count = count( $products );

		return $product_count > 0;
	}
}
