name: Release Smoke Test CI

on:
  pull_request:
    branches:
      - master

jobs:

    check-versions:
        name: Check versions
        runs-on: ubuntu-20.04
        outputs:
          release_version: ${{ steps.export.outputs.version }}

        steps:

            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Check Versions
              run: |
                bash ./bin/check-versions.sh
                RELEASE_VERSION=$( awk '/"version":/ {print}' composer.json | sed 's/[^0-9.]*\([0-9.]*\).*/\1/' )
                echo "RELEASE_VERSION=${RELEASE_VERSION}" >> $GITHUB_ENV

            - name: Export release version
              id: export
              run: echo "::set-output name=version::$RELEASE_VERSION"

    php-coding-standards:
        needs: check-versions
        name: PHP
        uses: ./.github/workflows/check-coding-standards.yml

    # setup:
    #     name: NodeJS
    #     needs: php-coding-standards
    #     uses: ./.github/workflows/setup-node.yml

    # linting-tests:
    #    name: Linting
    #    needs: setup
    #    uses: ./.github/workflows/run-linting.yml
