name: Release Smoke Test CI

on:
  pull_request:
    branches:
      - master

jobs:

    check-versions:
        if: startsWith(github.head_ref, 'release/')
        name: Check versions
        runs-on: ubuntu-20.04

        steps:

            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Check Versions
              run: |
                bash ./bin/check-versions.sh

    # php-coding-standards:
    #     needs: check-versions
    #     name: PHP
    #     uses: ./.github/workflows/check-coding-standards.yml

    handle-comment:
      name: Add PR Comment
      runs-on: ubuntu-latest

      steps:

          - name: Check PR Comment
              needs: check-versions
              id: check_comment
              run: |
                body=$(echo -n ':white_check_mark: This pull request has passed all tests and is ready to be merged.')
                existing_comment=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/comments | jq -r ".[] | select(.user.login == \"${{ github.actor }}\") | select(.body == \"${body}\") | .id")
                if [ "$existing_comment" != "" ]; then
                  echo "::set-output name=comment_created::true"
                else
                  echo "::set-output name=comment_created::false"
                fi

          - name: Add PR Comment
            if: ${{ success() && steps.check_comment.outputs.comment_created != 'true' }}
            run: |
              curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -X POST -d '{"body": ":white_check_mark: This pull request has passed all tests and is ready to be merged."}' "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/comments"

    # setup:
    #     name: NodeJS
    #     needs: php-coding-standards
    #     uses: ./.github/workflows/setup-node.yml

    # linting-tests:
    #    name: Linting
    #    needs: setup
    #    uses: ./.github/workflows/run-linting.yml
